// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI5kQ8SyYBpkcx_WsiBbsebEkpy3M9218',
    appId: '1:255305502265:web:4d6182179e3096564847e8',
    messagingSenderId: '255305502265',
    projectId: 'speechlab-31612',
    authDomain: 'speechlab-31612.firebaseapp.com',
    storageBucket: 'speechlab-31612.appspot.com',
    measurementId: 'G-KXLNBYYVH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK2pMnp7DJ8G5Dp27umU-U1KHMc_ZgsS8',
    appId: '1:255305502265:android:028ecbaea5c2ab804847e8',
    messagingSenderId: '255305502265',
    projectId: 'speechlab-31612',
    storageBucket: 'speechlab-31612.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA15rsK_s9KxDiDuo3xt-CZb3YjHZaVUdo',
    appId: '1:255305502265:ios:1ead0fc80d7a0d3d4847e8',
    messagingSenderId: '255305502265',
    projectId: 'speechlab-31612',
    storageBucket: 'speechlab-31612.appspot.com',
    iosBundleId: 'com.example.speechlabDashboard',
  );
}
